---
- hosts: vm2
  roles:
    # Only change permissions
    - role: change_permissions
      vars:
        target_path: "/etc/myconfig"
        target_permissions: "0755"

    # Only change owner and group
    - role: change_permissions
      vars:
        target_path: "/var/www"
        target_owner: "www-data"
        target_group: "www-data"

    # Change all attributes
    - role: change_permissions
      vars:
        target_path: "/opt/app"
        target_permissions: "0644"
        target_owner: "appuser"
        target_group: "appgroup"